skills_list = {'javascript': 'JavaScript ES6+',
               'python': 'Python',
               'c+': 'Python',
               'ruby': 'Ruby',
               'html': 'HTML & CSS & SCSS',
               'css': 'HTML & CSS & SCSS',
               'framework': 'React.js',
               'react': 'React.js',
               'angular': 'React.js',
               'vue': 'React.js',
               'spring': 'Node.js',
               'java': 'Node.js',
               'php': 'Node.js',
               'node': 'Node.js',
               'express': 'Express.js',
               'sql': 'SQL - PostgreSQL',
               'database': 'SQL - PostgreSQL',
               'nosql': 'NoSQL - MongoDB',
               'mongo': 'NoSQL - MongoDB',
               'non-relational': 'NoSQL - MongoDB',
               'test': {'word': 'Unit Testing - Mocha & Chai, Jest, Cypress, Storybook', 'not': ['greatest', 'latest']},
               'git': {'word': 'Git Version Control & GitHub', 'not': ['digital']},
               'algorithm': 'Algorithms',
               'nextjs': 'NextJS',
               'next.js': 'NextJS',
               'jquery': 'jQuery',
               'bootstrap': 'Bootstrap',
               'typescript': 'TypeScript - currently learning',
               'figma': 'Figma',
               'canva': 'Canva',
               'manage': 'Project Management',
               'selenium': 'Selenium',
               'tailwind': 'Tailwind CSS',
               'graphics': '3D Graphics',
               'responsive design': 'Responsive Design',
               'mobile': 'Mobile',
               'web design': 'Web Design',
               'xd': 'Adobe XD',
               'photoshop': 'Photoshop',
               'marketing': 'Marketing',
               'unity': {'word': 'Unity', 'not': ['community', 'opportunity']},
               'game': 'Unity',
               'gaming': 'Unity',
               'postman': 'Postman',
               'communication': 'Communication',
               'collaboration': 'Collaboration',
               'team': 'Teamwork',
               'problem': 'Problem Solving',
               'solv': 'Problem Solving',
               'bachelor': 'Engineering',
               'degree': 'Engineering',
               'engineering': 'Engineering',
               'computer science': 'Engineering',
               'rest': "RESTful API's",
               'soap': "RESTful API's",
               'api': {'word': "RESTful API's", 'not': ['rapid', 'rapidly', 'interested', 'zapier']},
               'ajax': "AJAX",
               'json': "JSON",
               'django': 'Django/Flask',
               'flask': 'Django/Flask',
               'frontend': 'Front-End Web Development',
               'front-end': 'Front-End Web Development',
               'backend': 'Back-End Web Development',
               'back-end': 'Back-End Web Development',
               'fullstack': 'Full-Stack Web Development',
               'full-stack': 'Full-Stack Web Development',
               'agile': 'Agile & Scrum',
               'scrum': 'Agile & Scrum',
               'wirefram': 'Wireframing',
               'websocket': 'WebSockets',
               'bash': 'Unix Shell Scripting - Bash',
               'unix': 'Unix Shell Scripting - Bash',
               'shell': 'Unix Shell Scripting - Bash',
               'material ui': 'Material UI',
               'object': 'Object Oriented Programming',
               'oop': 'Object Oriented Programming',
               'async': 'Asynchronous Programming',
               'crm': 'Customer Relations',
               'microsoft': 'Microsoft Technologies',
               'autocad': 'AutoCAD',
               'graphics': '3D Graphics',
               'vscode': 'Visual Studio Code',
               'visual studio': 'Visual Studio Code',
               'animation': 'Animation',
               'microsoft office': 'Microsoft Office',
               'ms office': 'Microsoft Office',
               'seo': 'SEO',
               'search engine optimization': 'Search Engine Optimization',
               }
