skills_list = {'javascript': 'JavaScript ES6+',
               'python': 'Python',
               'ruby': 'Ruby',
               'html': 'HTML & CSS & SCSS',
               'css': 'HTML & CSS & SCSS',
               'react': 'React.js',
               'node': 'Node.js',
               'express': 'Express.js',
               'sql': 'SQL - PostgreSQL',
               'nosql': 'NoSQL - MongoDB',
               'test': 'Unit Testing - Mocha & Chai, Jest, Cypress, Storybook',
               'git': 'Git Version Control & GitHub',
               'algorithm': 'Algorithms',
               'next': 'NextJS',
               'jquery': 'jQuery',
               'bootstrap': 'Bootstrap',
               'typescript': 'TypeScript - currently learning',
               'figma': 'Figma',
               'manage': 'Project Management',
               'selenium': 'Selenium',
               'tailwind': 'Tailwind CSS',
               'graphics': '3D Graphics',
               'responsive design': 'Responsive Design',
               'mobile': 'Mobile',
               'web design': 'Web Design',
               'adobe xd': 'Adobe XD',
               'marketing': 'Marketing',
               'unity': 'Unity',
               'postman': 'Postman',
               'communication': 'Communication',
               'collaboration': 'Collaboration',
               'teamwork': 'Teamwork',
               'self development': 'Self Development',
               'problem solv': 'Problem Solving',
               'engineering': 'Engineering',
               'api': "RESTful API's",
               'django': 'Django/Flask',
               'flask': 'Django/Flask',
               'frontend': 'Front-End Web Development',
               'front-end': 'Front-End Web Development',
               'fullstack': 'Full-Stack Web Development',
               'full-stack': 'Full-Stack Web Development',
               'agile': 'Agile & Scrum',
               'scrum': 'Agile & Scrum',
               'wire': 'Wireframing',
               'websocket': 'WebSockets',
               'bash': 'Linux Shell Scripting - Bash',
               'material ui': 'Material UI',
               'object orient': 'Object Oriented Programming',
               'oop': 'Object Oriented Programming',
               }